<?php

namespace Database\Seeders;

use App\Models\KelompokPenerimaManfaat;
use App\Models\UnitSppg;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class KelompokPenerimaManfaatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $unitSppg = UnitSppg::where('id_sppg', 'QQCV0LUG')->first() ?: UnitSppg::first();
        $unitId = $unitSppg ? $unitSppg->id : 1;

        // SPPG Center: Lat -8.1634360, Long 115.0771640 (Jl. Raya Angling Darma, Tegallinggah, Sukasada)
        // 18 KPM (14 Satuan Pendidikan + 4 Posyandu) terdistribusi mengitari SPPG
        // Semua nomor telepon diawali kode negara 62 (contoh: 6285739...)
        $sekolahDanPosyandu = [
            // 1. RA Baitul Mutaallim (Mundukkunci - Timur Laut, ~650m)
            [
                'id' => 1,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'RA Baitul Mutaallim',
                'kategori' => 'RA',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '69752881',
                'nama_kepala' => 'Hasanah S.Pd.I.',
                'telepon_kepala' => '6287762676756',
                'email_kepala' => 'asnahimbaled@gmail.com',
                'nama_pic' => 'Hasanah S.Pd.I.',
                'telepon_pic' => '6287762676756',
                'email_pic' => 'asnah9969@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Mundukkunci, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1585200,
                'longitude' => 115.0814500,
                'total_laki_laki' => 28,
                'total_perempuan' => 35,
                'total_porsi_kecil' => 58,
                'total_porsi_besar' => 5,
                'total_penerima' => 63,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],

            // 2. TK Al-Khairiyah Arsyadiyah (Tegallinggah - Timur Laut, ~1.0km)
            [
                'id' => 2,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'TK Al-Khairiyah Arsyadiyah',
                'kategori' => 'TK',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '69991873',
                'nama_kepala' => 'Nurhayati',
                'telepon_kepala' => '6285923528009',
                'email_kepala' => 'yayasanalkhairiyaharsyadiyah@gmail.com',
                'nama_pic' => 'Nur Kipti Hidana S.Pd.',
                'telepon_pic' => '6287862827059',
                'email_pic' => 'anaskiptihidana@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1568400,
                'longitude' => 115.0841200,
                'total_laki_laki' => 28,
                'total_perempuan' => 32,
                'total_porsi_kecil' => 54,
                'total_porsi_besar' => 6,
                'total_penerima' => 60,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 1,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Telur', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                ],
            ],

            // 3. TK Rare Kumara (Mundukkunci - Utara, ~850m)
            [
                'id' => 3,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'TK Rare Kumara',
                'kategori' => 'TK',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '69871319',
                'nama_kepala' => 'Made Mei Sumariani',
                'telepon_kepala' => '6281915664629',
                'email_kepala' => 'meisumariani19@gmail.com',
                'nama_pic' => 'Made Mei Sumariani',
                'telepon_pic' => '6281915664629',
                'email_pic' => 'meisumariani19@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Mundukkunci, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1559800,
                'longitude' => 115.0782000,
                'total_laki_laki' => 7,
                'total_perempuan' => 9,
                'total_porsi_kecil' => 14,
                'total_porsi_besar' => 2,
                'total_penerima' => 16,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],

            // 4. SD Negeri 2 Tegallinggah (Mundukkunci - Barat Laut, ~1.1km)
            [
                'id' => 4,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'SD Negeri 2 Tegallinggah',
                'kategori' => 'SD',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '50100647',
                'nama_kepala' => 'Putu Adi Purnawan, S.Pd.SD',
                'telepon_kepala' => '628124648150',
                'email_kepala' => 'sdnegeri2tegallinggah@gmail.com',
                'nama_pic' => 'Ni Luh Yuni Arini, S.Pd.',
                'telepon_pic' => '6287840006437',
                'email_pic' => 'yuniarini90@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Mundukkunci, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1548200,
                'longitude' => 115.0724500,
                'total_laki_laki' => 102,
                'total_perempuan' => 94,
                'total_porsi_kecil' => 79,
                'total_porsi_besar' => 117,
                'total_penerima' => 196,
                'alergi_porsi_kecil' => 2,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Telur', 'porsi_kecil' => 1, 'porsi_besar' => 0],
                    ['jenis_alergi' => 'Susu Sapi / Laktosa', 'porsi_kecil' => 1, 'porsi_besar' => 0],
                ],
            ],

            // 5. MIN 3 Buleleng (Mundukkunci - Barat, ~950m)
            [
                'id' => 5,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'MIN 3 Buleleng',
                'kategori' => 'MI',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '60721568',
                'nama_kepala' => 'Drs. Safrudin, M.Pd.I',
                'telepon_kepala' => '6281338635702',
                'email_kepala' => 'min.tegalinggah@gmail.com',
                'nama_pic' => 'Arie Saefudin Machlis, S.Pd.',
                'telepon_pic' => '6285739455513',
                'email_pic' => 'saefudindamayanti@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Mundukkunci, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1611000,
                'longitude' => 115.0688000,
                'total_laki_laki' => 191,
                'total_perempuan' => 229,
                'total_porsi_kecil' => 211,
                'total_porsi_besar' => 209,
                'total_penerima' => 420,
                'alergi_porsi_kecil' => 8,
                'alergi_porsi_besar' => 6,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Telur', 'porsi_kecil' => 4, 'porsi_besar' => 3],
                    ['jenis_alergi' => 'Ikan Laut / Seafood', 'porsi_kecil' => 3, 'porsi_besar' => 2],
                    ['jenis_alergi' => 'Kacang Tanah & Pohon', 'porsi_kecil' => 1, 'porsi_besar' => 1],
                ],
            ],

            // 6. MTs Al-Khairiyah (Mundukkunci - Barat Daya, ~1.1km)
            [
                'id' => 6,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'MTs Al-Khairiyah',
                'kategori' => 'MTs',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '69895243',
                'nama_kepala' => 'Abdul Wahab,S.Ag',
                'telepon_kepala' => '6281915664253',
                'email_kepala' => 'mtsalkhairiyah1986@gmail.com',
                'nama_pic' => 'Suniyati, S.Pd.',
                'telepon_pic' => '6281236917056',
                'email_pic' => 'suniyatisunjafer@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Mundukkunci, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1692500,
                'longitude' => 115.0691500,
                'total_laki_laki' => 85,
                'total_perempuan' => 76,
                'total_porsi_kecil' => 0,
                'total_porsi_besar' => 161,
                'total_penerima' => 161,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 4,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Telur', 'porsi_kecil' => 0, 'porsi_besar' => 2],
                    ['jenis_alergi' => 'Ikan Laut / Seafood', 'porsi_kecil' => 0, 'porsi_besar' => 2],
                ],
            ],

            // 7. MA Syamsul Huda (Mundukkunci - Selatan/Barat Daya, ~1.3km)
            [
                'id' => 7,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'MA Syamsul Huda',
                'kategori' => 'MA',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '60105476',
                'nama_kepala' => 'Baitulloh, S.Pd.I',
                'telepon_kepala' => '6281915637772',
                'email_kepala' => 'syamsulhudamasda@gmail.com',
                'nama_pic' => 'Mukhlishah',
                'telepon_pic' => '6285737044709',
                'email_pic' => 'ega.alvian2021@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Mundukkunci, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1741200,
                'longitude' => 115.0718000,
                'total_laki_laki' => 47,
                'total_perempuan' => 58,
                'total_porsi_kecil' => 0,
                'total_porsi_besar' => 105,
                'total_penerima' => 105,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 13,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Telur', 'porsi_kecil' => 0, 'porsi_besar' => 6],
                    ['jenis_alergi' => 'Ikan Laut / Seafood', 'porsi_kecil' => 0, 'porsi_besar' => 4],
                    ['jenis_alergi' => 'Susu Sapi / Laktosa', 'porsi_kecil' => 0, 'porsi_besar' => 3],
                ],
            ],

            // 8. RA Ar Rahmah (Tegallinggah - Selatan, ~1.5km)
            [
                'id' => 8,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'RA Ar Rahmah',
                'kategori' => 'RA',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '69752882',
                'nama_kepala' => 'Siti Rohmah, S.Pd.',
                'telepon_kepala' => '6287863124900',
                'email_kepala' => 'ra.arrahmah.tgl@gmail.com',
                'nama_pic' => 'Siti Rohmah, S.Pd.',
                'telepon_pic' => '6287863124900',
                'email_pic' => 'ra.arrahmah.tgl@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1764500,
                'longitude' => 115.0759000,
                'total_laki_laki' => 19,
                'total_perempuan' => 24,
                'total_porsi_kecil' => 38,
                'total_porsi_besar' => 5,
                'total_penerima' => 43,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],

            // 9. TK Catur Kumara (Tegallinggah - Tenggara, ~1.2km)
            [
                'id' => 9,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'TK Catur Kumara',
                'kategori' => 'TK',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '69871320',
                'nama_kepala' => 'Ni Nyoman Suastini',
                'telepon_kepala' => '6281915667822',
                'email_kepala' => 'tkcaturkumara@gmail.com',
                'nama_pic' => 'Ni Nyoman Suastini',
                'telepon_pic' => '6281915667822',
                'email_pic' => 'tkcaturkumara@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1728000,
                'longitude' => 115.0831000,
                'total_laki_laki' => 3,
                'total_perempuan' => 9,
                'total_porsi_kecil' => 10,
                'total_porsi_besar' => 2,
                'total_penerima' => 12,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 1,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Telur', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                ],
            ],

            // 10. SD Negeri 1 Tegallinggah (Tegallinggah - Timur/Tenggara, ~1.4km)
            [
                'id' => 10,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'SD Negeri 1 Tegallinggah',
                'kategori' => 'SD',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '50100646',
                'nama_kepala' => 'Ketut Sukadana, S.Pd.SD',
                'telepon_kepala' => '6287863116551',
                'email_kepala' => 'sdn1tegallinggah@gmail.com',
                'nama_pic' => 'Komang Budarsana, S.Pd.',
                'telepon_pic' => '6287863124806',
                'email_pic' => 'komangbudarsana6@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1672000,
                'longitude' => 115.0886000,
                'total_laki_laki' => 67,
                'total_perempuan' => 56,
                'total_porsi_kecil' => 67,
                'total_porsi_besar' => 56,
                'total_penerima' => 123,
                'alergi_porsi_kecil' => 1,
                'alergi_porsi_besar' => 4,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Telur', 'porsi_kecil' => 1, 'porsi_besar' => 2],
                    ['jenis_alergi' => 'Ikan Laut / Seafood', 'porsi_kecil' => 0, 'porsi_besar' => 2],
                ],
            ],

            // 11. SD Negeri 4 Tegallinggah (Batu Rancang - Timur/Timur Laut, ~1.3km)
            [
                'id' => 11,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'SD Negeri 4 Tegallinggah',
                'kategori' => 'SD',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '50100649',
                'nama_kepala' => 'Ketut Widiasa, S.Pd.SD',
                'telepon_kepala' => '6281338781744',
                'email_kepala' => 'sdn4tgl@gmail.com',
                'nama_pic' => 'Komang Hendra Mahardika, S.Pd',
                'telepon_pic' => '6281936551608',
                'email_pic' => 'hendra.mahardika19@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Batu Rancang, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1604500,
                'longitude' => 115.0882000,
                'total_laki_laki' => 38,
                'total_perempuan' => 24,
                'total_porsi_kecil' => 24,
                'total_porsi_besar' => 38,
                'total_penerima' => 62,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],

            // 12. MIS Abul'Abbas NW (Tegallinggah - Timur Laut, ~1.1km)
            [
                'id' => 12,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => "MIS Abul'Abbas NW",
                'kategori' => 'MI',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '60721565',
                'nama_kepala' => 'Nurleli, S.Pd.I',
                'telepon_kepala' => '6281337583647',
                'email_kepala' => 'mis.abulabbas@gmail.com',
                'nama_pic' => 'Nurleli, S.Pd.I',
                'telepon_pic' => '6281337583647',
                'email_pic' => 'nurlely724@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1561000,
                'longitude' => 115.0849000,
                'total_laki_laki' => 70,
                'total_perempuan' => 53,
                'total_porsi_kecil' => 55,
                'total_porsi_besar' => 68,
                'total_penerima' => 123,
                'alergi_porsi_kecil' => 1,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Telur', 'porsi_kecil' => 1, 'porsi_besar' => 0],
                ],
            ],

            // 13. MTs Abul'Abbas NW (Tegallinggah - Utara, ~1.2km)
            [
                'id' => 13,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => "MTs Abul'Abbas NW",
                'kategori' => 'MTs',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '69895244',
                'nama_kepala' => 'M. Zaini, S.Pd.I',
                'telepon_kepala' => '6281915668900',
                'email_kepala' => 'mtsabulabbasnw@gmail.com',
                'nama_pic' => 'M. Zaini, S.Pd.I',
                'telepon_pic' => '6281915668900',
                'email_pic' => 'mtsabulabbasnw@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1532000,
                'longitude' => 115.0795000,
                'total_laki_laki' => 29,
                'total_perempuan' => 21,
                'total_porsi_kecil' => 0,
                'total_porsi_besar' => 50,
                'total_penerima' => 50,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 7,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Telur', 'porsi_kecil' => 0, 'porsi_besar' => 4],
                    ['jenis_alergi' => 'Ikan Laut / Seafood', 'porsi_kecil' => 0, 'porsi_besar' => 3],
                ],
            ],

            // 14. SD Negeri 1 Selat (Selat - Barat Daya, ~2.1km)
            [
                'id' => 14,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'SD Negeri 1 Selat',
                'kategori' => 'SD',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '50100650',
                'nama_kepala' => 'I Ketut Astawa, S.Pd.SD',
                'telepon_kepala' => '6281338520336',
                'email_kepala' => 'sdn1selat@gmail.com',
                'nama_pic' => 'I Made Suardika, S.Pd.',
                'telepon_pic' => '6287860124889',
                'email_pic' => 'madesuardika@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Selat',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Jl. Raya Selat, Desa Selat, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1782000,
                'longitude' => 115.0654000,
                'total_laki_laki' => 80,
                'total_perempuan' => 68,
                'total_porsi_kecil' => 45,
                'total_porsi_besar' => 103,
                'total_penerima' => 148,
                'alergi_porsi_kecil' => 4,
                'alergi_porsi_besar' => 4,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Telur', 'porsi_kecil' => 2, 'porsi_besar' => 2],
                    ['jenis_alergi' => 'Ikan Laut / Seafood', 'porsi_kecil' => 2, 'porsi_besar' => 2],
                ],
            ],

            // 15. Posyandu Melati Mundukkunci (Mundukkunci - Barat Laut Dekat, ~500m)
            [
                'id' => 15,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'Posyandu Melati Mundukkunci',
                'kategori' => 'Posyandu',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'TPK',
                'kode_identitas' => 'POSY-510801-001',
                'nama_kepala' => 'Ni Ketut Wardani',
                'telepon_kepala' => '6287861884920',
                'email_kepala' => 'wardanikadek028@gmail.com',
                'nama_pic' => 'Ni Ketut Wardani',
                'telepon_pic' => '6287861884920',
                'email_pic' => 'wardanikadek028@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Mundukkunci, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1608000,
                'longitude' => 115.0741000,
                'jumlah_kader' => 5,
                'total_laki_laki' => 60,
                'total_perempuan' => 68,
                'total_porsi_kecil' => 86,
                'total_porsi_besar' => 42,
                'total_penerima' => 128,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],

            // 16. Posyandu Ratna Tegallinggah Atas (Tegallinggah Atas - Timur Laut Dekat, ~700m)
            [
                'id' => 16,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'Posyandu Ratna Tegallinggah Atas',
                'kategori' => 'Posyandu',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'TPK',
                'kode_identitas' => 'POSY-510801-002',
                'nama_kepala' => 'Kadek Sulendri',
                'telepon_kepala' => '6287754320911',
                'email_kepala' => 'sulendrikadek@gmail.com',
                'nama_pic' => 'Kadek Sulendri',
                'telepon_pic' => '6287754320911',
                'email_pic' => 'sulendrikadek@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah Atas, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1601000,
                'longitude' => 115.0825000,
                'jumlah_kader' => 5,
                'total_laki_laki' => 29,
                'total_perempuan' => 50,
                'total_porsi_kecil' => 57,
                'total_porsi_besar' => 22,
                'total_penerima' => 79,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],

            // 17. Posyandu Mawar Tegallinggah Bawah (Tegallinggah Bawah - Tenggara, ~800m)
            [
                'id' => 17,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'Posyandu Mawar Tegallinggah Bawah',
                'kategori' => 'Posyandu',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'TPK',
                'kode_identitas' => 'POSY-510801-003',
                'nama_kepala' => 'Luh Sudi Ariani',
                'telepon_kepala' => '6287861663833',
                'email_kepala' => 'radaniasriportoilbuleleng@gmail.com',
                'nama_pic' => 'Luh Sudi Ariani',
                'telepon_pic' => '6287861663833',
                'email_pic' => 'radaniasriportoilbuleleng@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah Bawah, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1691000,
                'longitude' => 115.0818000,
                'jumlah_kader' => 5,
                'total_laki_laki' => 24,
                'total_perempuan' => 41,
                'total_porsi_kecil' => 49,
                'total_porsi_besar' => 16,
                'total_penerima' => 65,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],

            // 18. Posyandu Sandat Lebah Pupuan (Lebah Pupuan - Barat Daya, ~850m)
            [
                'id' => 18,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'Posyandu Sandat Lebah Pupuan',
                'kategori' => 'Posyandu',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'TPK',
                'kode_identitas' => 'POSY-510801-004',
                'nama_kepala' => 'Luh Swastini',
                'telepon_kepala' => '6281805785157',
                'email_kepala' => 'luhswastini87@gmail.com',
                'nama_pic' => 'Luh Swastini',
                'telepon_pic' => '6281805785157',
                'email_pic' => 'luhswastini87@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Lebah Pupuan, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1685000,
                'longitude' => 115.0721000,
                'jumlah_kader' => 5,
                'total_laki_laki' => 17,
                'total_perempuan' => 37,
                'total_porsi_kecil' => 33,
                'total_porsi_besar' => 21,
                'total_penerima' => 54,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],
        ];

        foreach ($sekolahDanPosyandu as $data) {
            $data['uid'] = (string) Str::uuid();
            // Sanitasi otomatis memastikan format nomor telepon selalu diawali 62
            if (!empty($data['telepon_kepala'])) {
                $clean = preg_replace('/\D/', '', $data['telepon_kepala']);
                if (str_starts_with($clean, '0')) $clean = substr($clean, 1);
                if (!str_starts_with($clean, '62')) $clean = '62' . $clean;
                $data['telepon_kepala'] = $clean;
            }
            if (!empty($data['telepon_pic'])) {
                $clean = preg_replace('/\D/', '', $data['telepon_pic']);
                if (str_starts_with($clean, '0')) $clean = substr($clean, 1);
                if (!str_starts_with($clean, '62')) $clean = '62' . $clean;
                $data['telepon_pic'] = $clean;
            }
            KelompokPenerimaManfaat::create($data);
        }
    }
}
