<?php

namespace Database\Seeders;

use App\Models\KelompokPenerimaManfaat;
use App\Models\UnitSppg;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class KelompokPenerimaManfaatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $driver = DB::getDriverName();
        if ($driver === 'pgsql') {
            DB::statement('TRUNCATE TABLE kelompok_penerima_manfaat RESTART IDENTITY CASCADE;');
        } elseif ($driver === 'sqlite') {
            DB::statement('PRAGMA foreign_keys = OFF;');
            DB::table('kelompok_penerima_manfaat')->delete();
            DB::statement('DELETE FROM sqlite_sequence WHERE name = "kelompok_penerima_manfaat";');
            DB::statement('PRAGMA foreign_keys = ON;');
        } else {
            DB::table('kelompok_penerima_manfaat')->delete();
        }

        $unitSppg = UnitSppg::where('id_sppg', 'QQCV0LUG')->first() ?: UnitSppg::first();
        $unitId = $unitSppg ? $unitSppg->id : 1;

        // SPPG Center: Lat -8.1634360, Long 115.0771640 (Jl. Raya Angling Darma, Tegallinggah, Sukasada)
        // 18 KPM (14 Satuan Pendidikan + 4 Posyandu) disinkronkan dengan data terkini di database
        $sekolahDanPosyandu = [
            // 1. RA Baitul Mutaallim
            [
                'id' => 1,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'RA Baitul Mutaallim',
                'kategori' => 'RA',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '69752881',
                'nama_kepala' => 'Hasanah.S.Pd.I.',
                'telepon_kepala' => '6287762676756',
                'email_kepala' => 'mutaallimbaitul@gmail.com',
                'nama_pic' => 'Hasanah.S.Pd.I.',
                'telepon_pic' => '6287762676756',
                'email_pic' => 'nur069969@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Mundukkunci, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.15852,
                'longitude' => 115.08145,
                'total_laki_laki' => 28,
                'total_perempuan' => 35,
                'total_porsi_kecil' => 58,
                'total_porsi_besar' => 5,
                'total_penerima' => 63,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],
            // 2. TK Al-Khairiyah Arsyadiyah
            [
                'id' => 2,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'TK Al-Khairiyah Arsyadiyah',
                'kategori' => 'TK',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '69991873',
                'nama_kepala' => 'Nurhayati',
                'telepon_kepala' => '6285923528009',
                'email_kepala' => 'yayasanalkhairiyaharsyadiyah@gmail.com',
                'nama_pic' => 'Nur Kipli Hidana S.Pd.',
                'telepon_pic' => '6287828270691',
                'email_pic' => 'anakilpihidana@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.15684,
                'longitude' => 115.08412,
                'total_laki_laki' => 29,
                'total_perempuan' => 33,
                'total_porsi_kecil' => 56,
                'total_porsi_besar' => 6,
                'total_penerima' => 62,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 1,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Udang', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                ],
            ],
            // 3. TK Rare Kumara
            [
                'id' => 3,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'TK Rare Kumara',
                'kategori' => 'TK',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '69871319',
                'nama_kepala' => 'Made Mei Sumarianti',
                'telepon_kepala' => '6281915664629',
                'email_kepala' => 'meisumarianti19@gmail.com',
                'nama_pic' => 'Made Mei Sumarianti',
                'telepon_pic' => '6281915664629',
                'email_pic' => 'meisumarianti19@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Mundukkunci, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.15598,
                'longitude' => 115.0782,
                'total_laki_laki' => 7,
                'total_perempuan' => 9,
                'total_porsi_kecil' => 14,
                'total_porsi_besar' => 2,
                'total_penerima' => 16,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],
            // 4. SD Negeri 2 Tegallinggah
            [
                'id' => 4,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'SD Negeri 2 Tegallinggah',
                'kategori' => 'SD',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '50100647',
                'nama_kepala' => 'Putu Adi Parmawan, S.Pd.SD',
                'telepon_kepala' => '628124648150',
                'email_kepala' => 'sdnegeriduategallinggah@gmail.com',
                'nama_pic' => 'Ni Luh Yuni Arini, S.Pd.',
                'telepon_pic' => '6287840066437',
                'email_pic' => 'yuniarini90@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Mundukkunci, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.15482,
                'longitude' => 115.07245,
                'total_laki_laki' => 102,
                'total_perempuan' => 94,
                'total_porsi_kecil' => 79,
                'total_porsi_besar' => 117,
                'total_penerima' => 196,
                'alergi_porsi_kecil' => 2,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Daging Sapi', 'porsi_kecil' => 2, 'porsi_besar' => 0],
                ],
            ],
            // 5. MIN 3 Buleleng
            [
                'id' => 5,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'MIN 3 Buleleng',
                'kategori' => 'MI',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '60721568',
                'nama_kepala' => 'Drs. Safrudin, M.Pd.I',
                'telepon_kepala' => '6281338635702',
                'email_kepala' => 'min.tegallinggah@gmail.com',
                'nama_pic' => 'Arie Saefudin Muchlis, S.Pd.',
                'telepon_pic' => '6285739455513',
                'email_pic' => 'saefudindamayanti@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Mundukkunci, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1611,
                'longitude' => 115.0688,
                'total_laki_laki' => 191,
                'total_perempuan' => 229,
                'total_porsi_kecil' => 211,
                'total_porsi_besar' => 209,
                'total_penerima' => 420,
                'alergi_porsi_kecil' => 15,
                'alergi_porsi_besar' => 5,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Udang', 'porsi_kecil' => 2, 'porsi_besar' => 3],
                    ['jenis_alergi' => 'Susu dan produk olahannya', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                    ['jenis_alergi' => 'Telur Puyuh', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                    ['jenis_alergi' => 'Mie', 'porsi_kecil' => 1, 'porsi_besar' => 0],
                    ['jenis_alergi' => 'Saos', 'porsi_kecil' => 1, 'porsi_besar' => 0],
                    ['jenis_alergi' => 'Cokelat/Kakao', 'porsi_kecil' => 1, 'porsi_besar' => 0],
                    ['jenis_alergi' => 'Sosis', 'porsi_kecil' => 5, 'porsi_besar' => 0],
                    ['jenis_alergi' => 'Nugget', 'porsi_kecil' => 4, 'porsi_besar' => 0],
                    ['jenis_alergi' => 'Minuman Kemasan', 'porsi_kecil' => 1, 'porsi_besar' => 0],
                ],
            ],
            // 6. MTs Al-Khairiyah
            [
                'id' => 6,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'MTs Al-Khairiyah',
                'kategori' => 'MTs',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '69895243',
                'nama_kepala' => 'Abdul Wahab,S.Ag',
                'telepon_kepala' => '6281915664253',
                'email_kepala' => 'mtsalkhairiyah1986@gmail.com',
                'nama_pic' => 'Suriyati, S.Pd.',
                'telepon_pic' => '6281236917056',
                'email_pic' => 'suriyatihasanjafar@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Mundukkunci, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.16925,
                'longitude' => 115.06915,
                'total_laki_laki' => 85,
                'total_perempuan' => 76,
                'total_porsi_kecil' => 0,
                'total_porsi_besar' => 161,
                'total_penerima' => 161,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 4,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Udang', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                    ['jenis_alergi' => 'Nasi/Beras', 'porsi_kecil' => 0, 'porsi_besar' => 2],
                    ['jenis_alergi' => 'Ikan Asin', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                ],
            ],
            // 7. MA Syamsul Huda
            [
                'id' => 7,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'MA Syamsul Huda',
                'kategori' => 'MA',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '60105476',
                'nama_kepala' => 'Baitullah, S.Pd.I.',
                'telepon_kepala' => '6281915637772',
                'email_kepala' => 'syamsulhudamasda@gmail.com',
                'nama_pic' => 'Muzdalifah',
                'telepon_pic' => '6287856704409',
                'email_pic' => 'ega.alvian2021@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1721,
                'longitude' => 115.0748,
                'total_laki_laki' => 47,
                'total_perempuan' => 58,
                'total_porsi_kecil' => 0,
                'total_porsi_besar' => 105,
                'total_penerima' => 105,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 17,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Telur', 'porsi_kecil' => 0, 'porsi_besar' => 3],
                    ['jenis_alergi' => 'Daging Ayam', 'porsi_kecil' => 0, 'porsi_besar' => 5],
                    ['jenis_alergi' => 'Udang', 'porsi_kecil' => 0, 'porsi_besar' => 3],
                    ['jenis_alergi' => 'Santan', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                    ['jenis_alergi' => 'Kacang Tanah', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                    ['jenis_alergi' => 'Hati Ayam', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                    ['jenis_alergi' => 'Mie', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                    ['jenis_alergi' => 'Ikan Tongkol', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                    ['jenis_alergi' => 'Ikan Teri', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                ],
            ],
            // 8. RA Ar Rahmah
            [
                'id' => 8,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'RA Ar Rahmah',
                'kategori' => 'RA',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '69750176',
                'nama_kepala' => 'Yuni Fitriani',
                'telepon_kepala' => '6285954548047',
                'email_kepala' => 'arrahmahra98@gmail.com',
                'nama_pic' => 'Hilda Safira',
                'telepon_pic' => '6287786052411',
                'email_pic' => 'hildasafira2000@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1495,
                'longitude' => 115.0872,
                'total_laki_laki' => 19,
                'total_perempuan' => 24,
                'total_porsi_kecil' => 38,
                'total_porsi_besar' => 5,
                'total_penerima' => 43,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],
            // 9. TK Catur Kumara
            [
                'id' => 9,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'TK Catur Kumara',
                'kategori' => 'TK',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '69909381',
                'nama_kepala' => 'Luh Puspa Dewi Mawarni, S.Pd.',
                'telepon_kepala' => '6287763851734',
                'email_kepala' => 'puspadewi8612@gmail.com',
                'nama_pic' => 'Luh Puspa Dewi Mawarni, S.Pd.',
                'telepon_pic' => '6287763851734',
                'email_pic' => 'puspadewi8612@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1561,
                'longitude' => 115.0863,
                'total_laki_laki' => 3,
                'total_perempuan' => 9,
                'total_porsi_kecil' => 10,
                'total_porsi_besar' => 2,
                'total_penerima' => 12,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 1,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Udang', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                ],
            ],
            // 10. SD Negeri 1 Tegallinggah
            [
                'id' => 10,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'SD Negeri 1 Tegallinggah',
                'kategori' => 'SD',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '50100417',
                'nama_kepala' => 'Nyoman Tri Wardiyasa, S.Pd, SD.',
                'telepon_kepala' => '6281237882134',
                'email_kepala' => 'sdnsatutegallinggah@gmail.com',
                'nama_pic' => 'Made Sri Wismawan, S.Pd.',
                'telepon_pic' => '6287863259484',
                'email_pic' => 'madesriwismawan37@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1578,
                'longitude' => 115.0854,
                'total_laki_laki' => 67,
                'total_perempuan' => 56,
                'total_porsi_kecil' => 67,
                'total_porsi_besar' => 56,
                'total_penerima' => 123,
                'alergi_porsi_kecil' => 1,
                'alergi_porsi_besar' => 4,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Telur', 'porsi_kecil' => 1, 'porsi_besar' => 0],
                    ['jenis_alergi' => 'Sosis', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                    ['jenis_alergi' => 'Udang', 'porsi_kecil' => 0, 'porsi_besar' => 3],
                ],
            ],
            // 11. SD Negeri 4 Tegallinggah
            [
                'id' => 11,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'SD Negeri 4 Tegallinggah',
                'kategori' => 'SD',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '50100607',
                'nama_kepala' => 'Komang Ariantini, S.Pd.',
                'telepon_kepala' => '6285792460309',
                'email_kepala' => 'sdnegeri4tegallinggah@gmail.com',
                'nama_pic' => 'Gede Suardana, S.Pd.',
                'telepon_pic' => '6282146357299',
                'email_pic' => 'grahasanga78@gmai.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1512,
                'longitude' => 115.0898,
                'total_laki_laki' => 38,
                'total_perempuan' => 24,
                'total_porsi_kecil' => 24,
                'total_porsi_besar' => 38,
                'total_penerima' => 62,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],
            // 12. MIS Abul`Abbas NW
            [
                'id' => 12,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'MIS Abul`Abbas NW',
                'kategori' => 'MI',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '60729513',
                'nama_kepala' => 'Baehaki, S.Pd.I.',
                'telepon_kepala' => '6281803722850',
                'email_kepala' => 'miabulabbasnw11@mail.com',
                'nama_pic' => 'Arif Rahman Hakim, S.Pd.',
                'telepon_pic' => '6287760265603',
                'email_pic' => 'arahmanhkin@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Bukitsari, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1589,
                'longitude' => 115.0662,
                'total_laki_laki' => 70,
                'total_perempuan' => 53,
                'total_porsi_kecil' => 55,
                'total_porsi_besar' => 68,
                'total_penerima' => 123,
                'alergi_porsi_kecil' => 1,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Udang', 'porsi_kecil' => 1, 'porsi_besar' => 0],
                ],
            ],
            // 13. MTs Abul`Abbas NW
            [
                'id' => 13,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'MTs Abul`Abbas NW',
                'kategori' => 'MTs',
                'jenis_kepemilikan' => 'Swasta',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '69976411',
                'nama_kepala' => 'Syaripudin, S.Pd.I.',
                'telepon_kepala' => '6285938308988',
                'email_kepala' => 'mtsabulabbasnw@mail.com',
                'nama_pic' => 'Ulfa Hidayah, S.Pd.',
                'telepon_pic' => '6285338258545',
                'email_pic' => 'ulfahidayah1994@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Bukitsari, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1593,
                'longitude' => 115.0658,
                'total_laki_laki' => 29,
                'total_perempuan' => 21,
                'total_porsi_kecil' => 0,
                'total_porsi_besar' => 50,
                'total_penerima' => 50,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 7,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Jamur', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                    ['jenis_alergi' => 'Udang', 'porsi_kecil' => 0, 'porsi_besar' => 5],
                    ['jenis_alergi' => 'Ikan Laut', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                ],
            ],
            // 14. SD Negeri 1 Selat
            [
                'id' => 14,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'SD Negeri 1 Selat',
                'kategori' => 'SD',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'NPSN',
                'kode_identitas' => '50100440',
                'nama_kepala' => 'Gede Sukanata, S.Ag.',
                'telepon_kepala' => '6285857115972',
                'email_kepala' => 'sdno1selat@gmail.com',
                'nama_pic' => 'Ketut Askara, S.Pd.',
                'telepon_pic' => '6281338057370',
                'email_pic' => 'ketutaskara1968@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Selat',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Selat, Desa Selat, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1691,
                'longitude' => 115.0984,
                'total_laki_laki' => 80,
                'total_perempuan' => 68,
                'total_porsi_kecil' => 45,
                'total_porsi_besar' => 103,
                'total_penerima' => 148,
                'alergi_porsi_kecil' => 4,
                'alergi_porsi_besar' => 4,
                'keterangan_alergi' => [
                    ['jenis_alergi' => 'Daging Sapi', 'porsi_kecil' => 2, 'porsi_besar' => 3],
                    ['jenis_alergi' => 'Udang', 'porsi_kecil' => 1, 'porsi_besar' => 0],
                    ['jenis_alergi' => 'Telur', 'porsi_kecil' => 1, 'porsi_besar' => 0],
                    ['jenis_alergi' => 'Ikan Tongkol', 'porsi_kecil' => 0, 'porsi_besar' => 1],
                ],
            ],
            // 15. Posyandu Melati Mundukkunci
            [
                'id' => 15,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'Posyandu Melati Mundukkunci',
                'kategori' => 'Posyandu',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'TPK',
                'kode_identitas' => '5408052043004',
                'nama_kepala' => 'Mustari',
                'telepon_kepala' => '6287786014885',
                'email_kepala' => 'mustariarsya884@gmail.com',
                'nama_pic' => 'Mustari',
                'telepon_pic' => '6287786014885',
                'email_pic' => 'mustariarsya884@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Mundukkunci, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1581,
                'longitude' => 115.0802,
                'jumlah_kader' => 5,
                'total_laki_laki' => 60,
                'total_perempuan' => 68,
                'total_porsi_kecil' => 86,
                'total_porsi_besar' => 42,
                'total_penerima' => 128,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],
            // 16. Posyandu Ratna Tegallinggah Atas
            [
                'id' => 16,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'Posyandu Ratna Tegallinggah Atas',
                'kategori' => 'Posyandu',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'TPK',
                'kode_identitas' => '5208052023002',
                'nama_kepala' => 'Endang Hartati',
                'telepon_kepala' => '6287762037545',
                'email_kepala' => 'azamdaimullah9@gmail.com',
                'nama_pic' => 'Endang Hartati',
                'telepon_pic' => '6287762037545',
                'email_pic' => 'azamdaimullah9@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah Atas, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1565,
                'longitude' => 115.0839,
                'jumlah_kader' => 5,
                'total_laki_laki' => 29,
                'total_perempuan' => 50,
                'total_porsi_kecil' => 57,
                'total_porsi_besar' => 22,
                'total_penerima' => 79,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],
            // 17. Posyandu Mawar Tegallinggah Bawah
            [
                'id' => 17,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'Posyandu Mawar Tegallinggah Bawah',
                'kategori' => 'Posyandu',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'TPK',
                'kode_identitas' => '5108052013001',
                'nama_kepala' => 'Luh Sudi Ariani',
                'telepon_kepala' => '6287761663833',
                'email_kepala' => 'sudiarianipartaulibuleleng@gmail.com',
                'nama_pic' => 'Luh Sudi Ariani',
                'telepon_pic' => '6287861663833',
                'email_pic' => 'sudiarianipartaulibuleleng@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Tegallinggah Bawah, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1572,
                'longitude' => 115.0851,
                'jumlah_kader' => 5,
                'total_laki_laki' => 24,
                'total_perempuan' => 41,
                'total_porsi_kecil' => 49,
                'total_porsi_besar' => 16,
                'total_penerima' => 65,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],
            // 18. Posyandu Sandat Lebah Pupuan
            [
                'id' => 18,
                'unit_sppg_id' => $unitId,
                'nama_kelompok' => 'Posyandu Sandat Lebah Pupuan',
                'kategori' => 'Posyandu',
                'jenis_kepemilikan' => 'Negeri',
                'tipe_identitas' => 'TPK',
                'kode_identitas' => '5308052033002',
                'nama_kepala' => 'Luh Swastini',
                'telepon_kepala' => '6281805785157',
                'email_kepala' => 'luhsuastinii87@gmail.com',
                'nama_pic' => 'Luh Swastini',
                'telepon_pic' => '6281805785157',
                'email_pic' => 'luhsuastinii87@gmail.com',
                'provinsi' => 'Bali',
                'kabupaten' => 'Buleleng',
                'kecamatan' => 'Sukasada',
                'desa_kelurahan' => 'Tegallinggah',
                'kode_pos' => '81161',
                'alamat_lengkap' => 'Br. Dinas Lebah Pupuan, Desa Tegallinggah, Kec. Sukasada, Kab. Buleleng, Bali',
                'latitude' => -8.1601,
                'longitude' => 115.0885,
                'jumlah_kader' => 5,
                'total_laki_laki' => 17,
                'total_perempuan' => 37,
                'total_porsi_kecil' => 33,
                'total_porsi_besar' => 21,
                'total_penerima' => 54,
                'alergi_porsi_kecil' => 0,
                'alergi_porsi_besar' => 0,
                'keterangan_alergi' => [],
            ],
        ];

        foreach ($sekolahDanPosyandu as $data) {
            $data['uid'] = (string) Str::uuid();
            // Sanitasi otomatis memastikan format nomor telepon selalu diawali 62
            if (!empty($data['telepon_kepala'])) {
                $clean = preg_replace('/\D/', '', $data['telepon_kepala']);
                if (str_starts_with($clean, '0')) $clean = substr($clean, 1);
                if (!str_starts_with($clean, '62')) $clean = '62' . $clean;
                $data['telepon_kepala'] = $clean;
            }
            if (!empty($data['telepon_pic'])) {
                $clean = preg_replace('/\D/', '', $data['telepon_pic']);
                if (str_starts_with($clean, '0')) $clean = substr($clean, 1);
                if (!str_starts_with($clean, '62')) $clean = '62' . $clean;
                $data['telepon_pic'] = $clean;
            }
            KelompokPenerimaManfaat::create($data);
        }
    }
}
