/**
 * Standar Resmi Badan Gizi Nasional (BGN) & Preset Layout Stiker Box Label
 */

export const availableLogos = [
    {
        id: "bgn_logotype_main",
        name: "BGN Logotype Utama (Warna)",
        description: "Logo resmi lengkap dengan tulisan Badan Gizi Nasional",
        url: "/images/BGN_LOGOTYPE_MAIN.png",
        hasText: true,
    },
    {
        id: "bgn_logo_main",
        name: "BGN Lambang Utama (Warna)",
        description: "Hanya lambang logo bulat BGN berwarna",
        url: "/images/BGN_LOGO_MAIN.png",
        hasText: false,
    },
    {
        id: "bgn_logotype_white",
        name: "BGN Logotype Putih",
        description: "Logo lengkap teks untuk latar belakang gelap/warna",
        url: "/images/BGN_LOGOTYPE_MAIN_WHITE.png",
        hasText: true,
    },
    {
        id: "bgn_logotype_bw_b",
        name: "BGN Logotype Hitam Putih (Latar Terang)",
        description: "Logo lengkap teks hitam putih untuk cetak monokrom",
        url: "/images/BGN_LOGOTYPE_BW_B.png",
        hasText: true,
    },
    {
        id: "bgn_logotype_bw_w",
        name: "BGN Logotype Hitam Putih (Latar Gelap)",
        description: "Logo lengkap teks putih untuk latar gelap monokrom",
        url: "/images/BGN_LOGOTYPE_BW_w.png",
        hasText: true,
    },
    {
        id: "bgn_logo_bw_b",
        name: "BGN Lambang Hitam Putih (Latar Terang)",
        description: "Hanya lambang bulat hitam putih untuk latar terang",
        url: "/images/BGN_LOGO_BW_B.png",
        hasText: false,
    },
    {
        id: "bgn_logo_bw_w",
        name: "BGN Lambang Hitam Putih (Latar Gelap)",
        description: "Hanya lambang bulat hitam putih untuk latar gelap",
        url: "/images/BGN_LOGO_BW_W.png",
        hasText: false,
    },
];

export const bgnStandardElements = [
    {
        id: "el_logo",
        type: "logo",
        label: "Logo BGN",
        imageUrl: "/images/BGN_LOGOTYPE_MAIN.png",
        x: 3.5,
        y: 3.5,
        width: 38,
        height: 11,
        zIndex: 1,
        visible: true,
        isLocked: false,
    },
    {
        id: "el_sppg_header",
        type: "sppg_header",
        label: "Header SPPG Unit",
        x: 44,
        y: 3.5,
        width: 52.5,
        height: 11,
        textAlign: "right",
        zIndex: 1,
        visible: true,
        isLocked: false,
    },
    {
        id: "el_divider",
        type: "divider",
        label: "Garis Pembatas Emas",
        x: 3.5,
        y: 16,
        width: 93,
        height: 0.8,
        backgroundColor: "#C5921D",
        zIndex: 1,
        visible: true,
        isLocked: false,
    },
    {
        id: "el_badge",
        type: "badge",
        label: "Badge Judul",
        x: 3.5,
        y: 18.5,
        width: 44,
        height: 7,
        text: "LABEL MAKANAN BERGIZI GRATIS",
        backgroundColor: "#4E88C7",
        color: "#FFFFFF",
        fontSize: 10,
        zIndex: 2,
        visible: true,
        isLocked: false,
    },
    {
        id: "el_tanggal",
        type: "tanggal",
        label: "Tanggal Produksi",
        x: 3.5,
        y: 27.5,
        width: 44,
        height: 14,
        zIndex: 2,
        visible: true,
        isLocked: false,
    },
    {
        id: "el_jam",
        type: "jam",
        label: "Jam Produksi",
        x: 3.5,
        y: 43.5,
        width: 21,
        height: 14,
        zIndex: 2,
        visible: true,
        isLocked: false,
    },
    {
        id: "el_batas",
        type: "batas",
        label: "Batas Konsumsi",
        x: 26.5,
        y: 43.5,
        width: 21,
        height: 14,
        zIndex: 2,
        visible: true,
        isLocked: false,
    },
    {
        id: "el_tujuan",
        type: "tujuan",
        label: "Tujuan Pengantaran",
        x: 3.5,
        y: 59.5,
        width: 44,
        height: 16,
        zIndex: 2,
        visible: true,
        isLocked: false,
    },
    {
        id: "el_menu",
        type: "menu",
        label: "Kotak Menu",
        x: 52.5,
        y: 18.5,
        width: 44,
        height: 14,
        backgroundColor: "#4E88C7",
        zIndex: 2,
        visible: true,
        isLocked: false,
    },
    {
        id: "el_gizi",
        type: "nutrition_table",
        label: "Tabel Kandungan Gizi",
        x: 52.5,
        y: 34.5,
        width: 44,
        height: 41,
        zIndex: 2,
        visible: true,
        isLocked: false,
    },
    {
        id: "el_warning",
        type: "warning",
        label: "Banner Peringatan BGN",
        x: 3.5,
        y: 78.5,
        width: 93,
        height: 18,
        text: "MAKANAN INI HANYA UNTUK DIKONSUMSI DI TEMPAT.",
        subtitle: "DILARANG MEMBAWA PULANG!",
        zIndex: 3,
        visible: true,
        isLocked: false,
    },
];

export function getDefaultTemplatePresets() {
    return [
        {
            id: "bgn_standard_4_3",
            name: "Standar Resmi BGN (4:3)",
            description:
                "Format standar kemasan box resmi Badan Gizi Nasional berdimensi 4:3 lengkap dengan tabel gizi",
            is_default: true,
            aspect_ratio: "4/3",
            border_width: "3px",
            border_color: "#1E4B8B",
            border_radius: "1rem",
            canvas_bg: "#FFFFFF",
            canvas_padding: "8px",
            elements: JSON.parse(JSON.stringify(bgnStandardElements)),
        },
        {
            id: "compact_box_4_3",
            name: "Format Ringkas / Kompak (4:3)",
            description:
                "Tata letak lebih padat dengan border 2px untuk stiker box ukuran medium",
            is_default: false,
            aspect_ratio: "4/3",
            border_width: "2px",
            border_color: "#1E3A8A",
            border_radius: "0.75rem",
            canvas_bg: "#FFFFFF",
            canvas_padding: "6px",
            elements: JSON.parse(JSON.stringify(bgnStandardElements)),
        },
        {
            id: "square_box_1_1",
            name: "Format Tutup Persegi (1:1)",
            description:
                "Format kotak simetris (1:1) pas untuk ditempel di tengah tutup box makanan persegi",
            is_default: false,
            aspect_ratio: "1/1",
            border_width: "3px",
            border_color: "#0F766E",
            border_radius: "1.25rem",
            canvas_bg: "#FFFFFF",
            canvas_padding: "8px",
            elements: JSON.parse(JSON.stringify(bgnStandardElements)),
        },
        {
            id: "fast_print_no_gizi",
            name: "Format Cepat (Tanpa Tabel Gizi)",
            description:
                "Format praktis hanya fokus pada informasi Menu, Waktu, dan Tujuan Distribusi",
            is_default: false,
            aspect_ratio: "4/3",
            border_width: "2px",
            border_color: "#1E4B8B",
            border_radius: "1rem",
            canvas_bg: "#FFFFFF",
            canvas_padding: "8px",
            elements: bgnStandardElements.map((el) => {
                if (el.id === "el_gizi") {
                    return { ...el, visible: false };
                }
                if (el.id === "el_menu") {
                    return { ...el, width: 44, height: 28 };
                }
                return { ...el };
            }),
        },
    ];
}
